export const SN_FAQ_QUESTION = 'FAQQuestion'
export const FAQ_QUESTION_UPDATE_FAQ_QUESTIONS = SN_FAQ_QUESTION + '/UPDATE_FAQ_QUESTIONS'
export const FAQ_QUESTION_ADD_FAQ_QUESTION = SN_FAQ_QUESTION + '/ADD_FAQ_QUESTION'
